// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart/": {
            "get": {
                "description": "获取购物车里面的pkg列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "获取购物车里面的pkg列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.GetCartOutputElem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "加购物车",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "往购物车增添一个套餐",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "加购的套餐id",
                        "name": "pkgId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostCartInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除购物车条目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "删除购物车条目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "加购的套餐id",
                        "name": "cart_ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteCartEntriesInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "获取套餐种类列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "获取套餐种类列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.Category"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/diseases": {
            "get": {
                "description": "获取专项疾病列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "获取专项疾病列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.Disease"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login_register/": {
            "post": {
                "description": "登录或者注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "登录或者注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "captcha_code:图形验证码， sms_code:短信验证码",
                        "name": "loginBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.TokenOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login_register/captcha": {
            "get": {
                "description": "获取图片验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetCaptchaOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login_register/sms": {
            "get": {
                "description": "获取短信验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户手机号码",
                        "name": "mobile",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/orders/": {
            "get": {
                "description": "获取订单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "获取订单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页多少条",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "订单状态 -1 全部(默认值) 0-未付款，2-已付款(待预约), 3-已退款, 4-已关闭",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.PaginateListOutput"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/dto.ListOrderOutputEle"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建订单,返回前端调起微信支付的必须参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建订单的请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostOrderInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PostOrderOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "description": "获取订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "获取订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "订单的id, order_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RetrieveOrderOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "删除订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "订单的id, order_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/pay/scnd_pay": {
            "post": {
                "description": "根据订单id发起二次支付,返回前端调起微信支付的必须参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "根据订单id发起二次支付",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建订单的请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResourceID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PostOrderOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/pay/status": {
            "get": {
                "description": "前端轮询支付状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "查询订单支付状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单的prepay_id",
                        "name": "prepay_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.CheckPayStatusOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/pkg": {
            "get": {
                "description": "获取套餐列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "获取套餐列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页多少条",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "医院等级， 0-不限 1-公立三甲 2-公立医院 3-民营医院 4-专业机构",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "套餐类别id, 见字典项接口",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "价格区间左值, 0表示最小",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "价格区间左值, 0表示无上限",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "适用人群 0-不限 1-男士 2-女未婚 3-女已婚",
                        "name": "target",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "高发疾病, 见字典项接口",
                        "name": "disease_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "优先排序 0-默认排序，1-低价优先 2 高价优先",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.PaginateListOutput"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/dto.ListPackageOutputEle"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/pkg/{id}": {
            "get": {
                "description": "获取单个套餐详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "获取单个套餐详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "package id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetPackageOutPut"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/regions/": {
            "get": {
                "description": "根据parent_id获取行政区域列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regions"
                ],
                "summary": "根据parent_id获取行政区域列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "父级行政区域id， 默认值为第一级(省等)：0",
                        "name": "parent_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.Region"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/addrs": {
            "get": {
                "description": "获取收件地址列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addrs"
                ],
                "summary": "个人中心-\u003e账户信息-\u003e收件地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.UserAddr"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新增地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addrs"
                ],
                "summary": "新增用户收件地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增用户收件地址",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserAddrInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/addrs/{id}": {
            "get": {
                "description": "获取单个收件地址的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addrs"
                ],
                "summary": "获取单个收件地址的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "addr id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetUserAddrOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "修改单个收件地址的",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addrs"
                ],
                "summary": "修改单个收件地址的",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "addr id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改用户收件地址",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserAddrInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除单个收件地址的",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addrs"
                ],
                "summary": "删除单个收件地址的",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "addr id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/examinees": {
            "get": {
                "description": "获取常用体检人列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examinees"
                ],
                "summary": "个人中心-\u003e常用信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ListExamineeOutputEle"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新增常用体检人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examinees"
                ],
                "summary": "新增常用体检人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增常用体检人",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostExamineeInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/examinees/{id}": {
            "put": {
                "description": "修改单个常用体检人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examinees"
                ],
                "summary": "修改单个常用体检人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "examinee id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改单个常用体检人",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostExamineeInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除常用体检人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examinees"
                ],
                "summary": "删除常用体检人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "examinee id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "description": "获取用户的profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "个人中心-\u003e账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserDetailOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "修改个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "修改个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改个人信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PutUserProfileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResourceID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/profile/avatar": {
            "post": {
                "description": "上传个人头像",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "上传个人头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户上传头像",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UploadUserAvatarOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/profile/mobile": {
            "get": {
                "description": "获取用户手机号码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "获取用户手机号码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetUserMobileOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wx/enter": {
            "get": {
                "description": "拿到code后的回调地址",
                "tags": [
                    "WechatTag"
                ],
                "summary": "拿到code后的回调地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "微信服务器的code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.TokenOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wx/enter_url": {
            "get": {
                "description": "获取微信入口url",
                "tags": [
                    "WechatTag"
                ],
                "summary": "获取微信入口url",
                "parameters": [
                    {
                        "type": "string",
                        "description": "需要设置的button 入口，eg: '/index.html'",
                        "name": "uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "进入微信的url",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetEnterUrlOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wx/js_ticket": {
            "get": {
                "description": "获取jsApiTicket 签名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WechatTag"
                ],
                "summary": "获取签名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "传入需要的调用js-sdk的uri地址",
                        "name": "uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.JsApiTicketOutPut"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AggregatedOrderItem": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "order_id": {
                    "description": "套餐所属的order_id",
                    "type": "integer"
                },
                "pkg_avatar_url": {
                    "description": "套餐头像",
                    "type": "string"
                },
                "pkg_count": {
                    "description": "套餐数量",
                    "type": "integer"
                },
                "pkg_id": {
                    "description": "套餐id",
                    "type": "integer"
                },
                "pkg_name": {
                    "description": "套餐名称",
                    "type": "string"
                },
                "pkg_price": {
                    "description": "套餐单价",
                    "type": "number"
                }
            }
        },
        "dto.AggregatedOrderItemWithPkgItem": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "examinees": {
                    "description": "套餐检查人信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ExamineeInOrderItem"
                    }
                },
                "order_id": {
                    "description": "套餐所属的order_id",
                    "type": "integer"
                },
                "pkgItems": {
                    "description": "套餐检查项目",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PkgItemName"
                    }
                },
                "pkg_avatar_url": {
                    "description": "套餐头像",
                    "type": "string"
                },
                "pkg_count": {
                    "description": "套餐数量",
                    "type": "integer"
                },
                "pkg_id": {
                    "description": "套餐id",
                    "type": "integer"
                },
                "pkg_name": {
                    "description": "套餐名称",
                    "type": "string"
                },
                "pkg_price": {
                    "description": "套餐单价",
                    "type": "number"
                }
            }
        },
        "dto.CartItem": {
            "type": "object",
            "required": [
                "pkg_count",
                "pkg_id"
            ],
            "properties": {
                "cart_id": {
                    "description": "购物车条目id",
                    "type": "integer"
                },
                "examinees": {
                    "description": "体检人信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Examinee"
                    }
                },
                "pkg_count": {
                    "description": "套餐数量",
                    "type": "integer"
                },
                "pkg_id": {
                    "description": "套餐id",
                    "type": "integer"
                }
            }
        },
        "dto.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "类别(专项疾病)id",
                    "type": "integer"
                },
                "name": {
                    "description": "类别(专项疾病)名称",
                    "type": "string"
                }
            }
        },
        "dto.CheckPayStatusOutput": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "支付状态 0-待支付 2-支付成功 4-订单已关闭",
                    "type": "integer"
                }
            }
        },
        "dto.CreateUserAddrInput": {
            "type": "object",
            "required": [
                "building_detail",
                "city_id",
                "county_id",
                "province_id",
                "town_id"
            ],
            "properties": {
                "building_detail": {
                    "type": "string"
                },
                "city_id": {
                    "type": "integer"
                },
                "county_id": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "integer"
                },
                "province_id": {
                    "type": "integer"
                },
                "town_id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteCartEntriesInput": {
            "type": "object",
            "properties": {
                "cart_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.Disease": {
            "$ref": "#/definitions/dto.Category"
        },
        "dto.Examinee": {
            "type": "object",
            "required": [
                "examine_date",
                "examinee_mobile",
                "examinee_name",
                "gender",
                "id_card_no"
            ],
            "properties": {
                "examine_date": {
                    "description": "体检日期 时间戳， 精确到 日",
                    "type": "integer"
                },
                "examinee_mobile": {
                    "description": "体检人电话",
                    "type": "string"
                },
                "examinee_name": {
                    "description": "体检人姓名",
                    "type": "string"
                },
                "gender": {
                    "description": "性别 1-男 2-女",
                    "type": "integer"
                },
                "id_card_no": {
                    "description": "身份证号码",
                    "type": "string"
                },
                "is_married": {
                    "description": "婚否 1-是 2-否",
                    "type": "integer"
                }
            }
        },
        "dto.ExamineeInOrderItem": {
            "type": "object",
            "required": [
                "examine_date",
                "examinee_mobile",
                "examinee_name",
                "gender",
                "id_card_no"
            ],
            "properties": {
                "examine_date": {
                    "description": "体检日期 时间戳， 精确到 日",
                    "type": "integer"
                },
                "examinee_mobile": {
                    "description": "体检人电话",
                    "type": "string"
                },
                "examinee_name": {
                    "description": "体检人姓名",
                    "type": "string"
                },
                "gender": {
                    "description": "性别 1-男 2-女",
                    "type": "integer"
                },
                "id_card_no": {
                    "description": "身份证号码",
                    "type": "string"
                },
                "is_married": {
                    "description": "婚否 1-是 2-否",
                    "type": "integer"
                },
                "order_item_id": {
                    "description": "order item(订单项)的id",
                    "type": "integer"
                }
            }
        },
        "dto.GetCaptchaOutput": {
            "type": "object",
            "properties": {
                "captcha_img_url": {
                    "type": "string"
                }
            }
        },
        "dto.GetCartOutputElem": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "套餐头像url",
                    "type": "string"
                },
                "hospital_id": {
                    "description": "医院id",
                    "type": "integer"
                },
                "hospital_name": {
                    "description": "医院名字",
                    "type": "string"
                },
                "id": {
                    "description": "购物车条目id",
                    "type": "integer"
                },
                "name": {
                    "description": "套餐名字",
                    "type": "string"
                },
                "pkg_count": {
                    "description": "套餐数量",
                    "type": "integer"
                },
                "pkg_id": {
                    "description": "套餐id",
                    "type": "integer"
                },
                "pkg_price": {
                    "description": "套餐单价",
                    "type": "number"
                },
                "target": {
                    "description": "套餐目标人群 0-均可 1-男士 2-女未婚 3-女已婚",
                    "type": "integer"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "dto.GetEnterUrlOutput": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.GetPackageOutPut": {
            "type": "object",
            "properties": {
                "basic_info": {
                    "description": "套餐基本信息",
                    "type": "object",
                    "$ref": "#/definitions/dto.PackageBasicInfo"
                },
                "items": {
                    "description": "具体项目",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PackageItem"
                    }
                },
                "notices": {
                    "description": "套餐须知",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PackageNotice"
                    }
                },
                "procedure": {
                    "description": "套餐流程",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PackageProcedure"
                    }
                }
            }
        },
        "dto.GetUserAddrOutput": {
            "type": "object",
            "required": [
                "building_detail",
                "city_id",
                "county_id",
                "province_id",
                "town_id"
            ],
            "properties": {
                "building_detail": {
                    "type": "string"
                },
                "city_id": {
                    "type": "integer"
                },
                "county_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "integer"
                },
                "province_id": {
                    "type": "integer"
                },
                "town_id": {
                    "type": "integer"
                }
            }
        },
        "dto.GetUserMobileOutput": {
            "type": "object",
            "properties": {
                "mobile": {
                    "type": "string"
                }
            }
        },
        "dto.JsApiTicketOutPut": {
            "type": "object",
            "properties": {
                "signature": {
                    "description": "微信JsSDK签名",
                    "type": "string"
                }
            }
        },
        "dto.ListExamineeOutputEle": {
            "type": "object",
            "required": [
                "examinee_mobile",
                "examinee_name",
                "gender",
                "id_card_no",
                "is_married"
            ],
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "examinee_mobile": {
                    "description": "体检人电话",
                    "type": "string"
                },
                "examinee_name": {
                    "description": "体检人姓名",
                    "type": "string"
                },
                "gender": {
                    "description": "性别 1-男 2-女",
                    "type": "integer"
                },
                "id": {
                    "description": "Examinee 表的id",
                    "type": "integer"
                },
                "id_card_no": {
                    "description": "身份证号码",
                    "type": "string"
                },
                "is_married": {
                    "description": "婚否 1-是 2-否",
                    "type": "integer"
                },
                "relation": {
                    "description": "体检人与本人的关系 0 本人， 1 父亲， 2 兄弟姐妹， 3 儿子， 4 女儿， 5 母亲， 6 夫妻， 7 其他",
                    "type": "integer"
                }
            }
        },
        "dto.ListOrderOutputEle": {
            "type": "object",
            "properties": {
                "aggregated_order_items": {
                    "description": "订单中的套餐列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AggregatedOrderItem"
                    }
                },
                "amount": {
                    "description": "订单总价",
                    "type": "number"
                },
                "order_id": {
                    "description": "订单id",
                    "type": "integer"
                },
                "out_trade_no": {
                    "description": "订单号",
                    "type": "integer"
                },
                "status": {
                    "description": "订单状态 0-待付款，2-待预约(指已经付款) 3-已退款 4-已关闭 5-待评价",
                    "type": "integer"
                }
            }
        },
        "dto.ListPackageOutputEle": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "套餐头像",
                    "type": "string"
                },
                "hospital_id": {
                    "type": "integer"
                },
                "hospital_name": {
                    "description": "医院体检中心名字",
                    "type": "string"
                },
                "id": {
                    "description": "套餐id",
                    "type": "integer"
                },
                "level": {
                    "description": "医院等级， 0-不限 1-公立三甲 2-公立医院 3-民营医院 4-专业机构",
                    "type": "integer"
                },
                "name": {
                    "description": "套餐名字",
                    "type": "string"
                },
                "price_original": {
                    "description": "门市价, 原价, 单位分",
                    "type": "number"
                },
                "price_real": {
                    "description": "真实价格， 现价格， 单位分",
                    "type": "number"
                },
                "sold": {
                    "description": "已经预约的单数, 这个暂时需要前端用hidden隐藏起来",
                    "type": "integer"
                }
            }
        },
        "dto.LoginRegisterInput": {
            "type": "object",
            "required": [
                "captcha_code",
                "mobile",
                "sms_code"
            ],
            "properties": {
                "captcha_code": {
                    "description": "图形验证码",
                    "type": "string"
                },
                "latitude": {
                    "description": "注册时的纬度， 获取不到请传 0.0",
                    "type": "number"
                },
                "longitude": {
                    "description": "注册时的经度, 获取不到的话请传 0.0",
                    "type": "number"
                },
                "mobile": {
                    "description": "用户手机号码",
                    "type": "string"
                },
                "sms_code": {
                    "description": "短信验证码",
                    "type": "string"
                }
            }
        },
        "dto.PackageAttribute": {
            "type": "object",
            "properties": {
                "attr_type": {
                    "description": "套餐的属性类型， 1-套餐项目 2-套餐须知 3-套餐体检的流程",
                    "type": "integer"
                },
                "brief": {
                    "description": "属性概述",
                    "type": "string"
                },
                "comment": {
                    "description": "属性详情",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "属性名字",
                    "type": "string"
                },
                "order_no": {
                    "description": "属性排序， 小的排前面",
                    "type": "integer"
                },
                "pkg_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PackageBasicInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "套餐URL",
                    "type": "string"
                },
                "brief": {
                    "description": "套餐简介",
                    "type": "string"
                },
                "comment": {
                    "description": "套餐详细介绍",
                    "type": "string"
                },
                "hospital_id": {
                    "type": "integer"
                },
                "hospital_name": {
                    "description": "医院体检中心名称",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "套餐名称",
                    "type": "string"
                },
                "price_original": {
                    "description": "原价/门市价",
                    "type": "number"
                },
                "price_real": {
                    "description": "实际价格",
                    "type": "number"
                },
                "target": {
                    "description": "套餐目标人群 0-不限 1-男 2-未婚女 3-已婚女",
                    "type": "integer"
                },
                "tips": {
                    "description": "套餐提示",
                    "type": "string"
                }
            }
        },
        "dto.PackageItem": {
            "$ref": "#/definitions/dto.PackageAttribute"
        },
        "dto.PackageNotice": {
            "$ref": "#/definitions/dto.PackageAttribute"
        },
        "dto.PackageProcedure": {
            "$ref": "#/definitions/dto.PackageAttribute"
        },
        "dto.PaginateListOutput": {
            "type": "object",
            "properties": {
                "has_next": {
                    "description": "是否有下一页, 1 是， 0 否",
                    "type": "integer"
                },
                "list": {
                    "description": "列表数据",
                    "type": "object"
                },
                "page_no": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "本页实际条目数量",
                    "type": "integer"
                }
            }
        },
        "dto.PkgItemName": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "属性名字，此处是套餐项目名字",
                    "type": "string"
                },
                "order_no": {
                    "description": "属性排序， 小的排前面",
                    "type": "integer"
                }
            }
        },
        "dto.PostCartInput": {
            "type": "object",
            "properties": {
                "pkg_id": {
                    "description": "要添加的套餐id",
                    "type": "integer"
                }
            }
        },
        "dto.PostExamineeInput": {
            "type": "object",
            "required": [
                "examinee_mobile",
                "examinee_name",
                "id_card_no",
                "is_married"
            ],
            "properties": {
                "examinee_mobile": {
                    "description": "体检人电话",
                    "type": "string"
                },
                "examinee_name": {
                    "description": "体检人姓名",
                    "type": "string"
                },
                "id_card_no": {
                    "description": "身份证号码",
                    "type": "string"
                },
                "is_married": {
                    "description": "婚否 1-是 2-否",
                    "type": "integer"
                },
                "relation": {
                    "description": "体检人与本人的关系 0 本人， 1 父亲， 2 兄弟姐妹， 3 儿子， 4 女儿， 5 母亲， 6 夫妻， 7 其他",
                    "type": "integer"
                }
            }
        },
        "dto.PostOrderInput": {
            "type": "object",
            "required": [
                "cart_items",
                "subscriber_mobile"
            ],
            "properties": {
                "cart_items": {
                    "description": "订单项目",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CartItem"
                    }
                },
                "subscriber_comment": {
                    "type": "string"
                },
                "subscriber_mobile": {
                    "description": "预约人手机号",
                    "type": "string"
                }
            }
        },
        "dto.PostOrderOutput": {
            "type": "object",
            "properties": {
                "nonceStr": {
                    "type": "string"
                },
                "package": {
                    "type": "string"
                },
                "paySign": {
                    "type": "string"
                },
                "prePayId": {
                    "type": "string"
                },
                "signType": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.PutUserProfileInput": {
            "type": "object",
            "properties": {
                "gender": {
                    "description": "用户性别 1-男 2-女",
                    "type": "integer"
                },
                "update_time": {
                    "description": "这个参数请忽略， 不用管",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                }
            }
        },
        "dto.Region": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "省，市， 区/县， 镇/街道 的行政区域id",
                    "type": "integer"
                },
                "level": {
                    "description": "行政区域等级, 1-省，2-市， 3-区/县， 4-镇/街道",
                    "type": "integer"
                },
                "name": {
                    "description": "行政区域名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "该行政区域的父级id， 1级行政区域的父id 是 0",
                    "type": "integer"
                }
            }
        },
        "dto.ResourceID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.RetrieveOrderOutput": {
            "type": "object",
            "properties": {
                "aggregated_order_items_with_pkg_item": {
                    "description": "聚合后包括套餐项目的的order item",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AggregatedOrderItemWithPkgItem"
                    }
                },
                "amount": {
                    "description": "订单总价",
                    "type": "number"
                },
                "mobile": {
                    "description": "下单人/预约人手机号",
                    "type": "string"
                },
                "order_id": {
                    "description": "订单id",
                    "type": "integer"
                },
                "out_trade_no": {
                    "description": "订单号",
                    "type": "integer"
                },
                "remark": {
                    "description": "订单备注",
                    "type": "string"
                },
                "status": {
                    "description": "订单状态 0-待付款，2-待预约(指已经付款) 3-已退款 4-已关闭 5-待评价",
                    "type": "integer"
                }
            }
        },
        "dto.TokenOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserAddrInput": {
            "$ref": "#/definitions/dto.CreateUserAddrInput"
        },
        "dto.UploadUserAvatarOutput": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "头像url",
                    "type": "string"
                }
            }
        },
        "dto.UserDetailOutput": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mobile": {
                    "type": "string"
                },
                "open_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "middleware.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "ecode": {
                    "type": "integer"
                },
                "emsg": {
                    "type": "string"
                }
            }
        },
        "model.UserAddr": {
            "type": "object",
            "required": [
                "building_detail",
                "city_id",
                "county_id",
                "province_id",
                "town_id"
            ],
            "properties": {
                "building_detail": {
                    "type": "string"
                },
                "city_id": {
                    "type": "integer"
                },
                "city_name": {
                    "type": "string"
                },
                "county_id": {
                    "type": "integer"
                },
                "county_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "integer"
                },
                "province_id": {
                    "type": "integer"
                },
                "province_name": {
                    "type": "string"
                },
                "town_id": {
                    "type": "integer"
                },
                "town_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
